import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Brain Teaser",
  description: "Daily mathematical brain teasers — analysis, topology, probability, and more.",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-slate-50 text-slate-900 min-h-screen">
        <header className="bg-white border-b border-slate-200 sticky top-0 z-10">
          <div className="max-w-4xl mx-auto px-4 h-14 flex items-center justify-between">
            <Link href="/" className="font-bold text-slate-800 tracking-tight text-lg">
              🧮 Brain Teaser
            </Link>
            <nav className="flex items-center gap-5 text-sm font-medium text-slate-500">
              <Link href="/" className="hover:text-slate-900 transition-colors">Today</Link>
              <Link href="/archive" className="hover:text-slate-900 transition-colors">Archive</Link>
              <a
                href="https://github.com/LiSiruiRay/brain_teaser"
                target="_blank"
                rel="noopener noreferrer"
                className="hover:text-slate-900 transition-colors"
              >
                GitHub
              </a>
            </nav>
          </div>
        </header>
        <main className="max-w-4xl mx-auto px-4 py-8">{children}</main>
        <footer className="text-center text-xs text-slate-400 py-8">
          Generated by Claude · {new Date().getFullYear()}
        </footer>
      </body>
    </html>
  );
}
