"""
Builds README.md from local questions/ directory.
Source of truth: questions/Problem_list.md (index) + questions/{slug}/question.md (metadata via YAML frontmatter).
Run locally: python scripts/sync.py
"""

import re
from pathlib import Path
from datetime import datetime

REPO_ROOT = Path(__file__).parent.parent
PROBLEM_LIST = REPO_ROOT / "questions" / "Problem_list.md"


# ── Frontmatter parser (no external deps) ────────────────────────────────────

def parse_frontmatter(path: Path) -> dict:
    """Return dict of frontmatter fields, or {} if none found."""
    if not path.exists():
        return {}
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    block = text[3:end]
    meta = {}
    for line in block.splitlines():
        m = re.match(r"^(\w+):\s*(.+)$", line.strip())
        if not m:
            continue
        key, val = m.group(1), m.group(2).strip()
        # list:  ["a", "b", "c"]  or  []
        if val.startswith("["):
            items = re.findall(r'"([^"]*)"', val)
            meta[key] = items
        # bool
        elif val == "true":
            meta[key] = True
        elif val == "false":
            meta[key] = False
        # quoted string
        elif val.startswith('"') and val.endswith('"'):
            meta[key] = val[1:-1]
        # integer
        elif val.isdigit():
            meta[key] = int(val)
        else:
            meta[key] = val
    return meta


# ── Problem list parser ───────────────────────────────────────────────────────

def parse_problem_list():
    """Parse questions/Problem_list.md → list of {num, name, slug, date}."""
    text = PROBLEM_LIST.read_text(encoding="utf-8")
    entries = []
    for line in text.splitlines():
        if not line.startswith("|"):
            continue
        stripped = line.strip().strip("|")
        if re.match(r"[-| ]+$", stripped) or stripped.startswith("#"):
            continue
        cols = [c.strip() for c in stripped.split("|")]
        if len(cols) < 2:
            continue
        num, problem_link = cols[0], cols[1]
        if num == "#":
            continue
        m = re.match(r"\[(.+?)\]\((.+?)/question\.md\)", problem_link)
        if not m:
            continue
        name, slug = m.group(1), m.group(2)
        date = cols[2].strip() if len(cols) > 2 else ""
        entries.append({"num": num, "name": name, "slug": slug, "date": date})
    return entries


# ── README builder ────────────────────────────────────────────────────────────

def local_links(slug):
    q = REPO_ROOT / "questions" / slug / "question.md"
    a = REPO_ROOT / "questions" / slug / "answer.md"
    q_link = f"[view](questions/{slug}/question.md)" if q.exists() else ""
    a_link = f"[view](questions/{slug}/answer.md)" if a.exists() else ""
    return q_link, a_link


def fmt_tags(tags: list) -> str:
    return ", ".join(f"`{t}`" for t in tags) if tags else ""


def fmt_solved(val) -> str:
    if val is True:
        return "✅"
    return ""


def build_readme(entries):
    lines = [
        "# Brain Teaser\n",
        "> Last updated: " + datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC") + "\n",
        "",
        "## Problem Schedule\n",
        "![Problem Schedule](readme_imgs/problem_arrange.png)\n",
        "## Welcome",
        "",
        "This is a personal collection of small but beautiful mathematical problems — one a day, organized by topic.",
        "Problems come from Putnam, olympiads, probability puzzles, integration bees, complex analysis, differential geometry, ML/stats, and more.",
        "",
        "**Contributions and feedback are welcome!** Feel free to open an issue or PR if you have a problem to suggest, a cleaner solution, or a correction.",
        "",
        "---",
        "",
        "## Problem List\n",
        "| # | Name | Type | Tags | Date | Solved | Redo | Comments | Related | Question | Answer |",
        "|---|------|------|------|------|--------|------|----------|---------|----------|--------|",
    ]

    for e in entries:
        fm = parse_frontmatter(REPO_ROOT / "questions" / e["slug"] / "question.md")
        q_link, a_link = local_links(e["slug"])

        name     = fm.get("name", e["name"])
        type_    = fm.get("type", "")
        tags     = fmt_tags(fm.get("tags", []))
        date     = fm.get("date", e["date"])
        solved   = fmt_solved(fm.get("solved", False))
        redo     = str(fm.get("redo", 0)) if fm.get("redo", 0) else ""
        comments = fm.get("comments", "")
        related  = fmt_tags(fm.get("related", []))

        lines.append(
            f"| {e['num']} | {name} | {type_} | {tags} | {date} | {solved} | {redo} | {comments} | {related} | {q_link} | {a_link} |"
        )

    lines += ["", "---", "*Generated by [scripts/sync.py](scripts/sync.py) via GitHub Actions*"]
    return "\n".join(lines) + "\n"


def main():
    print("Reading questions/Problem_list.md...")
    entries = parse_problem_list()
    print(f"Found {len(entries)} entries. Building README...")
    readme_path = REPO_ROOT / "README.md"
    readme_path.write_text(build_readme(entries), encoding="utf-8")
    print(f"Done. Written to {readme_path}")


if __name__ == "__main__":
    main()
